### ISSUE TITLE
更新到v3.06.007

### ISSUE THREAD

**Issue by chenxiex** [id10tttt/cn.i4.I4Tools-flatpak#1]
爱思助手Linux已经更新到3.06.007，请求更新flatpak包。
rpm包下载地址：[https://d-updater.i4.cn/i4linux/deb/i4tools_v3.06.007.rpm](https://d-updater.i4.cn/i4linux/deb/i4tools_v3.06.007.rpm)
deb包下载地址：[https://d-updater.i4.cn/i4linux/deb/i4tools_v3.06.007.deb](https://d-updater.i4.cn/i4linux/deb/i4tools_v3.06.007.deb)

**Comment by id10tttt** [comment]
> 爱思助手Linux已经更新到3.06.007，请求更新flatpak包。 rpm包下载地址：https://d-updater.i4.cn/i4linux/deb/i4tools_v3.06.007.rpm deb包下载地址：https://d-updater.i4.cn/i4linux/deb/i4tools_v3.06.007.deb

更新了3.06.007。 我还以为爱思助手不更新了呢。

**Comment by chenxiex** [comment]
可用。唯一需要注意的是升级后`QT_AUTO_SCREEN_SCALE_FACTOR=1`不再生效。高分屏需要手动设置`QT_SCREEN_SCALE_FACTORS=放大倍数`。不过这是软件本身的问题。
